---
  - name: Add onlyoffice gpg keys
    ansible.builtin.apt_key:
      keyserver: "keyserver.ubuntu.com"
      id: "CB2DE8E5"
      state: present
    become: yes

  - name: Add onlyoffice repositories
    ansible.builtin.apt_repository:
      repo: "{{ package_repo }}"
      state: present
    become: yes

  - name: Add debian contrib repositories
    ansible.builtin.apt_repository:
      repo: "{{ debian_repo }}"
      state: present
    when: ansible_distribution == "Debian"
    become: yes

  - name: Install desktopeditors
    ansible.builtin.apt: 
      name: "{{ package_name }}"
      update_cache: yes
      state: latest
    become: yes
