---
- name: Include Debian variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Include Centos variables
  include_vars: "{{ ansible_os_family}}.yml"
  when: ansible_os_family == "RedHat"

- name: Include Windows variables
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}{{ ansible_architecture }}.yml"
    - "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == "Windows"

- name: Include Debian tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Include Centos install tasks
  include_tasks: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"
 
- name: Include Windows install tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Windows"
