---
  - name: Add onlyoffice repo
    dnf:
      name: "{{ onlyoffice_repo }}"
      disable_gpg_check: yes
    become: yes

  - name: Install epel repo
    dnf: 
      name: epel-release
    become: yes

  - name: Install desktopeditors
    dnf:
      name: "{{ package_name }}"
      update_cache: yes
      state: present
    become: yes
