---
- name: Download and install OnlyOffice desktopeditors
  ansible.windows.win_package:
    path: "{{ download_url }}"
    product_id: "{{ product_id }}"
    arguments:
      - /install
      - /verysilent
