---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_8
    image: docker.io/geerlingguy/docker-centos8-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible