---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_2004
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible