---
- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: Descktopeditors exist check
      stat:
        path: /bin/desktopeditors1
      register: bass_result
      failed_when: bass_result.stat.exists == False