---
- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: Descktopeditors exist check
      stat:
        path: /bin/desktopeditors1
      register: result
      failed_when: result.stat.exists == false