---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${MOLECULE_DISTRO}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  env:
    MOLECULE_NO_LOG: ${MOLECULE_NO_LOG:-true}
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
