---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_7
    image: docker.io/geerlingguy/docker-centos7-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible