---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian_10
    image: docker.io/geerlingguy/docker-debian10-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible