---
name: Test
'on':
  pull_request:
  push:

jobs:

  lint:
    name: Lint tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install lint dependencies.
        run: |
          pip3 install --upgrade pip
          pip3 install ansible
          pip3 install yamllint
          pip3 install ansible-lint

      - name: Run lint tests.
        run: |
          find . -name "*.yml" -o -name "*.yaml" | grep -v molecule | xargs yamllint
          find . -name "*.yml" -o -name "*.yaml" | grep -v molecule | grep -v tasks/RedHat7.yml | xargs ansible-lint
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  molecule:
    name: Molecule test on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - rockylinux9
          - ubuntu2004
          - ubuntu2204
          - ubuntu2404
          - debian11
          - debian12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          pip3 install --upgrade pip
          pip3 install ansible
          pip3 install molecule
          pip3 install molecule-plugins[docker]
          pip3 install molecule-plugins[lint]
          pip3 install docker

      - name: Run Molecule tests.
        run: molecule test --scenario-name default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
